CREATE TABLE `employee_onboarding` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`submitted_at` text NOT NULL,
	`reviewed_by` text,
	`reviewed_at` text,
	`full_name` text NOT NULL,
	`date_of_birth` text NOT NULL,
	`gender` text NOT NULL,
	`personal_email` text NOT NULL,
	`personal_phone` text NOT NULL,
	`current_address` text NOT NULL,
	`permanent_address` text,
	`emergency_contact_name` text NOT NULL,
	`emergency_contact_relationship` text NOT NULL,
	`emergency_contact_phone` text NOT NULL,
	`aadhaar_number` text NOT NULL,
	`pan_number` text NOT NULL,
	`aadhaar_upload_url` text,
	`pan_upload_url` text,
	`passport_upload_url` text,
	`photo_upload_url` text NOT NULL,
	`job_title` text NOT NULL,
	`department` text,
	`reporting_manager` text,
	`date_of_joining` text NOT NULL,
	`employment_type` text NOT NULL,
	`work_location` text NOT NULL,
	`highest_qualification` text,
	`degree_certificate_url` text,
	`technical_skills` text,
	`certifications_urls` text,
	`previous_company` text,
	`previous_job_title` text,
	`total_experience` text,
	`experience_letter_url` text,
	`uan_number` text,
	`last_salary_slip_url` text,
	`bank_account_number` text NOT NULL,
	`ifsc_code` text NOT NULL,
	`bank_name_branch` text NOT NULL,
	`cancelled_cheque_url` text NOT NULL,
	`tax_regime` text NOT NULL,
	`investment_proofs_url` text,
	`laptop_required` text NOT NULL,
	`software_access` text,
	`tshirt_size` text,
	`policy_agreements` text NOT NULL,
	`signature` text NOT NULL,
	`blood_group` text,
	`linkedin_profile` text,
	`special_accommodations` text,
	`about_yourself` text,
	`work_preferences` text,
	`career_goals` text,
	`hobbies` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`reviewed_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action
);
